### ISSUE TITLE
Error in shiny::isTruthy: attempt to apply non-function

### ISSUE THREAD

**Issue by shubhrampandey** [PaulC91/shinyauthr#51] opened 2021-04-23 06:01 UTC
I am getting this error in Rv4.0.4 and v4.0.5 and when I commented out below lines from the server the app runs perfectly.

  logout_init <- callModule(shinyauthr::logout,
                            id = "logout",
                            active = reactive(credentials()$user_auth))

  credentials <- callModule(shinyauthr::login,
                            id = "login",
                            data = user_base,
                            user_col = user,
                            pwd_col = password,
                            log_out = reactive(logout_init())
  )

Any help much appreciated.

**Comment by PaulC91** [comment] 2021-04-25 09:56
Hi there. 
Sorry I can't reproduce your error. Do you have the latest version of the package installed?
If you're still getting this error with the latest package versions could you try to post a minimal full app example that is not working and include your `sessionInfo()` ?
Thanks,
Paul

**Comment by PaulC91** [comment] 2021-07-15 11:35
closing this as I don't think this is a problem in the latest version of the package. let me know if you still have the issue.

**Closed by PaulC91** 2021-07-15 11:35 UTC
