### ISSUE TITLE
About loginUI title Simple Chinese does not work

### ISSUE THREAD

**Issue by woshiisp** [PaulC91/shinyauthr#37] opened 2020-07-12 09:46 UTC
The inside of the package loginUI title cannot support Simple Chinese display function parameters, unable to work at run time. Is there a way to solve?
Thank U very much

**Comment by PaulC91** [comment] 2020-07-13 10:59
Hi. Can you post a [simple reproducible example](https://reprex.tidyverse.org/) so I can try to debug the error? Thanks!

**Comment by woshiisp** [comment] 2020-07-13 13:53
thanks for replying.My app including five files: global.R,ui.R,ui01.R,ui02.R,server.R,returnClick.js.
My only question is that  the "title = " ,the parameter of  function shinyauthr::loginUI, is not suitable for Chinese！my codes list：

ui.R:


library(shiny)
library(shinydashboard)
library(dplyr)
library(shinyjs)
library(glue)
library(shinyauthr)
#library(showtext)
#font.add("kaishu","simkai.ttf")

ui <- dashboardPage(
  dashboardHeader(title = "shinyauthr",
                  tags$li(class = "dropdown", style = "padding: 8px;",
                          shinyauthr::logoutUI("logout")),
                  tags$li(class = "dropdown",tags$a(icon("github"), 
                                 href = "https://github.com/paulc91/shinyauthr",
                                 title = "See the code on github"))
  ),
  
  dashboardSidebar(collapsed = TRUE, 
                   div(textOutput("welcome"), style = "padding: 20px")
  ),
  
  dashboardBody(
    shinyjs::useShinyjs(),
    tags$head(tags$style(".table{margin: 0 auto;}"),
              #tags$script(src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.16/iframeResizer.contentWindow.min.js",
                          #type="text/javascript"),
              includeScript("returnClick.js")
    ),
    **shinyauthr::loginUI("login",title = "Please Login")**
    #uiOutput("user_table"),
    uiOutput("testUI"),
    HTML('<div data-iframe-height></div>')
  )
)


server.R:



source("ui02.R")

server <- function(input, output, session) {
  
  user_base <- data_frame(
    user = c("yh","user2"),
    password = c("yh", "pass2"), 
    password_hash = sapply(c("yh", "pass2"), sodium::password_store), 
    permissions = c("admin", "standard"),
    name = c("User One", "User Two")
  )
  
  
  
  
  credentials <- callModule(shinyauthr::login, "login",
                            data = user_base,
                            user_col = user,
                            pwd_col = password_hash,
                            sodium_hashed = TRUE,
                            log_out = reactive(logout_init()))
  
  logout_init <- callModule(shinyauthr::logout, "logout", reactive(credentials()$user_auth))
  
  observe({
    if(credentials()$user_auth) {
      shinyjs::removeClass(selector = "body", class = "sidebar-collapse")
    } else {
      shinyjs::addClass(selector = "body", class = "sidebar-collapse")
    }
  })
  
  
  
  user_info <- reactive({credentials()$info})
  
  user_data <- reactive({
    req(credentials()$user_auth)
    
    if (user_info()$permissions == "admin") {
      dplyr::starwars[,1:10]
    } else if (user_info()$permissions == "standard") {
      dplyr::storms[,1:11]
    }
    
  })
  
  output$welcome <- renderText({
    req(credentials()$user_auth)
    
    glue("Welcome {user_info()$name}")
  })
  
  
  output$testUI <- renderUI({
    req(credentials()$user_auth)
    ui02
  })
  
  
  output$distPlot <- renderPlot({
    
    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times")
    
  })
}

**Comment by PaulC91** [comment] 2020-07-13 14:01
This works for me...

```
library(shiny)
library(shinyauthr)
library(shinyjs)

# dataframe that holds usernames, passwords and other user data
user_base <- data.frame(
  user = c("user1", "user2"),
  password = c("pass1", "pass2"), 
  permissions = c("admin", "standard"),
  name = c("User One", "User Two"),
  stringsAsFactors = FALSE,
  row.names = NULL
)

ui <- fluidPage(
  # must turn shinyjs on
  shinyjs::useShinyjs(),
  # add logout button UI 
  div(class = "pull-right", logoutUI(id = "logout")),
  # add login panel UI function
  loginUI(id = "login", title = "测试标题"),
  # setup table output to show user info after login
  tableOutput("user_table")
)

server <- function(input, output, session) {
  
  # call the logout module with reactive trigger to hide/show
  logout_init <- callModule(shinyauthr::logout, 
                            id = "logout", 
                            active = reactive(credentials()$user_auth))
  
  # call login module supplying data frame, user and password cols
  # and reactive trigger
  credentials <- callModule(shinyauthr::login, 
                            id = "login", 
                            data = user_base,
                            user_col = user,
                            pwd_col = password,
                            log_out = reactive(logout_init()))
  
  # pulls out the user information returned from login module
  user_data <- reactive({credentials()$info})
  
  output$user_table <- renderTable({
    # use req to only render results when credentials()$user_auth is TRUE
    req(credentials()$user_auth)
    user_data()
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by woshiisp** [comment] 2020-07-14 00:53
I am confusing! In RStudio,changed the settings—— files-saving with encoding——UTF-8,and I runned the codes,then I got the following Errors :

my codes about LoginUI:shinyauthr::loginUI("login",title = "测试标题")

> runApp('shinyauth')

Listening on http://127.0.0.1:6156
Warning in checkEncoding(file) :
  The input file E:\RStudio work\shinyauth/ui.R does not seem to be encoded in UTF8
Warning in readLines(file, warn = FALSE) :
  输入链结'E:\RStudio work\shinyauth/ui.R'内的输入不对
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
  E:\RStudio work\shinyauth/ui.R:30:41: 意外的INCOMPLETE_STRING
29:     ),
30:     shinyauthr::loginUI("login",title = "
                                            ^
Warning: Error in sourceUTF8: Error sourcing C:\Users\A\AppData\Local\Temp\Rtmpyos0nQ\file17744a5d7003
  [No stack trace available]

**Comment by woshiisp** [comment] 2020-07-14 01:07
I just runned the codes ,it worked. I  don not know the reason.

**Comment by Vicellken** [comment] 2020-07-14 02:43
> I just runned the codes ,it worked. I don not know the reason.

might be something wrong with the quotation mark... or miserable cache in RStudio...

**Comment by PaulC91** [comment] 2020-07-14 10:15
So it's working fine now? I'll close the issue as this seems to be an encoding problem unrelated to shinyauthr. Let me know if you think it should remain open. Thanks!

**Closed by PaulC91** 2020-07-14 10:15 UTC

**Comment by woshiisp** [comment] 2020-07-14 10:19
Thanks!I had sloved the problem.I found the problem is about the system Encoding,it is not the programing. Thanks a lot!!!------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Paul&amp;nbsp;Campbell&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月14日(星期二) 晚上6:15
收件人:&nbsp;&quot;PaulC91/shinyauthr&quot;<shinyauthr@noreply.github.com&gt;;
抄送:&nbsp;&quot;Han&quot;<175210356@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaulC91/shinyauthr] About loginUI title Simple Chinese does not work (#37)
