### ISSUE TITLE
Problem if password contains §

### ISSUE THREAD

**Issue by bonedi** [PaulC91/shinyauthr#23] opened 2019-07-24 14:19 UTC
Hey,
First of all: Thanks for the great package.
I found out that you can't log in, if the passwort contains the character §. Don't know if there are other characters which will cause that bug also, I didn't find out.   
Minimal example:  
Just run your example app with:
`user_base <- data.frame(user = "test", password = "§test") ` 
It will always say "Invalid username or password!"  
Also if § isn't the first character, it will cause this bug.

**Comment by andodet** [comment] 2021-04-25 09:36
@bonedi Tried to reproduce your error withoout any luck, no idea if this still is a show-stopper for you. It'd be beneficial if you could provide your `sessionInfo()` output.

**Comment by PaulC91** [comment] 2021-07-20 13:52
Closing as I can't reproduce this problem either. 
Try reinstalling the package to the latest version if you're still having an issue with this. 
Thanks.

**Closed by PaulC91** 2021-07-20 13:52 UTC
